#!/bin/bash

if [[ -z $1 ]]; then
    echo "Usage: ./flac2m4a.sh [FLAC] [COVER]"
    exit
fi

FILE=$(ffprobe "$1" -v quiet -print_format json -show_format | jq .format.tags.title -r)

ffmpeg -i "$1" -acodec alac -vn "$FILE.m4a"
./AtomicParsley "$FILE.m4a" --artwork "$2" --comment "Generated By HBSpy"

TEMP=$(find . -name "$FILE-temp-*.m4a")

mv -f "$TEMP" "$FILE.m4a"

