#!/bin/bash

if [[ -z $1 ]]; then
    echo "Convert Non-163 FLAC -- WITHOUT cover in comment"
    echo "Usage: ./flac2m4a.sh [FLAC] [COVER]"
    exit
fi

FILE=$(ffprobe "$1" -v quiet -print_format json -show_format | jq .format.tags | jq 'with_entries( .key |= ascii_downcase )' | jq .title -r)
FILE=$(basename "$FILE")

echo $FILE

ffmpeg -i "$1" -acodec alac -vn "$FILE.m4a"
AtomicParsley "$FILE.m4a" --artwork "$2" --comment "Generated By HBSpy"

TEMP=$(find . -name "$FILE-temp-*.m4a")

mv -f "$TEMP" "$FILE.m4a"

